export const stableClubAutomationExecutorAbi = [
  {
    type: "function",
    name: "executeHarvestProposal",
    stateMutability: "nonpayable",
    inputs: [{ name: "proposalId", type: "bytes32" }],
    outputs: [],
  },
  {
    type: "function",
    name: "executeCompoundProposal",
    stateMutability: "nonpayable",
    inputs: [{ name: "proposalId", type: "bytes32" }],
    outputs: [],
  },
  {
    type: "function",
    name: "executeRebalanceProposal",
    stateMutability: "nonpayable",
    inputs: [{ name: "proposalId", type: "bytes32" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setAuthorizedKeeper",
    stateMutability: "nonpayable",
    inputs: [
      { name: "keeper", type: "address" },
      { name: "authorized", type: "bool" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "harvest",
    stateMutability: "nonpayable",
    inputs: [
      { name: "permissionId", type: "bytes32" },
      { name: "executionNonce", type: "uint256" },
      { name: "adapter", type: "address" },
      { name: "positionTokenId", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "compound",
    stateMutability: "nonpayable",
    inputs: [
      { name: "permissionId", type: "bytes32" },
      { name: "executionNonce", type: "uint256" },
      { name: "adapter", type: "address" },
      { name: "positionTokenId", type: "uint256" },
      { name: "rewardToken", type: "address" },
      { name: "tokenA", type: "address" },
      { name: "tokenB", type: "address" },
      { name: "swapAmount", type: "uint256" },
      { name: "minAmountOut", type: "uint256" },
      { name: "amountA", type: "uint256" },
      { name: "amountB", type: "uint256" },
      { name: "amountAMin", type: "uint256" },
      { name: "amountBMin", type: "uint256" },
      { name: "slippageBps", type: "uint256" },
      { name: "deadline", type: "uint256" },
      { name: "quotedAmountOut", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "rebalance",
    stateMutability: "nonpayable",
    inputs: [
      { name: "permissionId", type: "bytes32" },
      { name: "executionNonce", type: "uint256" },
      { name: "adapter", type: "address" },
      { name: "positionTokenId", type: "uint256" },
      { name: "tokenA", type: "address" },
      { name: "tokenB", type: "address" },
      { name: "newTickLower", type: "int24" },
      { name: "newTickUpper", type: "int24" },
      { name: "swapAmount", type: "uint256" },
      { name: "minAmountOut", type: "uint256" },
      { name: "closeAmountAMin", type: "uint256" },
      { name: "closeAmountBMin", type: "uint256" },
      { name: "mintAmountAMin", type: "uint256" },
      { name: "mintAmountBMin", type: "uint256" },
      { name: "slippageBps", type: "uint256" },
      { name: "deadline", type: "uint256" },
      { name: "quotedAmountOut", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "event",
    name: "AutomationExecuted",
    inputs: [
      { name: "permissionId", type: "bytes32", indexed: true },
      { name: "action", type: "uint8", indexed: false },
      { name: "poolId", type: "bytes32", indexed: true },
      { name: "user", type: "address", indexed: true },
      { name: "positionTokenId", type: "uint256", indexed: false },
      { name: "executionNonce", type: "uint256", indexed: false },
    ],
  },
] as const;

export const safetyControllerAbi = [
  {
    type: "function",
    name: "isAutomationPaused",
    stateMutability: "view",
    inputs: [{ name: "poolId", type: "bytes32" }],
    outputs: [{ name: "", type: "bool" }],
  },
] as const;

export const permissionRegistryAbi = [
  {
    type: "function",
    name: "permissionIdFor",
    stateMutability: "pure",
    inputs: [
      { name: "user", type: "address" },
      { name: "chainId", type: "uint256" },
      { name: "poolId", type: "bytes32" },
      { name: "tokenA", type: "address" },
      { name: "tokenB", type: "address" },
    ],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "permissionIdForScoped",
    stateMutability: "pure",
    inputs: [
      { name: "user", type: "address" },
      { name: "chainId", type: "uint256" },
      { name: "poolId", type: "bytes32" },
      { name: "tokenA", type: "address" },
      { name: "tokenB", type: "address" },
      { name: "scope", type: "bytes32" },
    ],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "registerPermission",
    stateMutability: "nonpayable",
    inputs: [
      {
        name: "perm",
        type: "tuple",
        components: [
          { name: "user", type: "address" },
          { name: "chainId", type: "uint256" },
          { name: "poolId", type: "bytes32" },
          { name: "tokenA", type: "address" },
          { name: "tokenB", type: "address" },
          { name: "allowedActions", type: "uint256" },
          { name: "maxAmountPerTx", type: "uint256" },
          { name: "maxAmountPerDay", type: "uint256" },
          { name: "maxSlippageBps", type: "uint256" },
          { name: "minTimeBetweenExecutions", type: "uint256" },
          { name: "maxExecutionsPerDay", type: "uint256" },
          { name: "expiresAt", type: "uint256" },
          { name: "revoked", type: "bool" },
          { name: "paused", type: "bool" },
        ],
      },
    ],
    outputs: [{ name: "permissionId", type: "bytes32" }],
  },
  {
    type: "function",
    name: "registerScopedPermission",
    stateMutability: "nonpayable",
    inputs: [
      {
        name: "perm",
        type: "tuple",
        components: [
          { name: "user", type: "address" },
          { name: "chainId", type: "uint256" },
          { name: "poolId", type: "bytes32" },
          { name: "tokenA", type: "address" },
          { name: "tokenB", type: "address" },
          { name: "allowedActions", type: "uint256" },
          { name: "maxAmountPerTx", type: "uint256" },
          { name: "maxAmountPerDay", type: "uint256" },
          { name: "maxSlippageBps", type: "uint256" },
          { name: "minTimeBetweenExecutions", type: "uint256" },
          { name: "maxExecutionsPerDay", type: "uint256" },
          { name: "expiresAt", type: "uint256" },
          { name: "revoked", type: "bool" },
          { name: "paused", type: "bool" },
        ],
      },
      { name: "scope", type: "bytes32" },
    ],
    outputs: [{ name: "permissionId", type: "bytes32" }],
  },
  {
    type: "function",
    name: "revoke",
    stateMutability: "nonpayable",
    inputs: [{ name: "permissionId", type: "bytes32" }],
    outputs: [],
  },
  {
    type: "function",
    name: "getPermission",
    stateMutability: "view",
    inputs: [{ name: "permissionId", type: "bytes32" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "user", type: "address" },
          { name: "chainId", type: "uint256" },
          { name: "poolId", type: "bytes32" },
          { name: "tokenA", type: "address" },
          { name: "tokenB", type: "address" },
          { name: "allowedActions", type: "uint256" },
          { name: "maxAmountPerTx", type: "uint256" },
          { name: "maxAmountPerDay", type: "uint256" },
          { name: "maxSlippageBps", type: "uint256" },
          { name: "minTimeBetweenExecutions", type: "uint256" },
          { name: "maxExecutionsPerDay", type: "uint256" },
          { name: "expiresAt", type: "uint256" },
          { name: "revoked", type: "bool" },
          { name: "paused", type: "bool" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "executionNonceUsed",
    stateMutability: "view",
    inputs: [
      { name: "permissionId", type: "bytes32" },
      { name: "executionNonce", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
] as const;

export const stableClubExecutorAbi = [
  {
    type: "function",
    name: "depositAndAddLiquidity",
    stateMutability: "nonpayable",
    inputs: [
      { name: "permissionId", type: "bytes32" },
      { name: "executionNonce", type: "uint256" },
      { name: "adapter", type: "address" },
      { name: "stablecoin", type: "address" },
      { name: "tokenA", type: "address" },
      { name: "tokenB", type: "address" },
      { name: "depositAmount", type: "uint256" },
      { name: "swapAmount", type: "uint256" },
      { name: "minAmountOut", type: "uint256" },
      { name: "minLpOut", type: "uint256" },
      { name: "slippageBps", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "removeLiquidity",
    stateMutability: "nonpayable",
    inputs: [
      { name: "permissionId", type: "bytes32" },
      { name: "executionNonce", type: "uint256" },
      { name: "adapter", type: "address" },
      { name: "tokenA", type: "address" },
      { name: "tokenB", type: "address" },
      { name: "lpAmount", type: "uint256" },
      { name: "minAmountA", type: "uint256" },
      { name: "minAmountB", type: "uint256" },
      { name: "slippageBps", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "withdrawAll",
    stateMutability: "nonpayable",
    inputs: [
      { name: "permissionId", type: "bytes32" },
      { name: "executionNonce", type: "uint256" },
      { name: "adapter", type: "address" },
      { name: "tokenA", type: "address" },
      { name: "tokenB", type: "address" },
      { name: "lpAmount", type: "uint256" },
      { name: "minAmountA", type: "uint256" },
      { name: "minAmountB", type: "uint256" },
      { name: "slippageBps", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "pauseAutomation",
    stateMutability: "nonpayable",
    inputs: [{ name: "permissionId", type: "bytes32" }],
    outputs: [],
  },
  {
    type: "function",
    name: "revokePermission",
    stateMutability: "nonpayable",
    inputs: [{ name: "permissionId", type: "bytes32" }],
    outputs: [],
  },
  {
    type: "function",
    name: "emergencyExit",
    stateMutability: "nonpayable",
    inputs: [
      { name: "permissionId", type: "bytes32" },
      { name: "executionNonce", type: "uint256" },
      { name: "adapter", type: "address" },
      { name: "tokenA", type: "address" },
      { name: "tokenB", type: "address" },
      { name: "lpAmount", type: "uint256" },
      { name: "minAmountA", type: "uint256" },
      { name: "minAmountB", type: "uint256" },
    ],
    outputs: [],
  },
] as const;

export const erc20Abi = [
  {
    type: "function",
    name: "approve",
    stateMutability: "nonpayable",
    inputs: [
      { name: "spender", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "balanceOf",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "allowance",
    stateMutability: "view",
    inputs: [
      { name: "owner", type: "address" },
      { name: "spender", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "decimals",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint8" }],
  },
] as const;

/** StableClubConcentratedLiquidityExecutor — five-pool deposit surface. */
export const concentratedLiquidityExecutorAbi = [
  {
    type: "function",
    name: "depositFivePoolStrategy",
    stateMutability: "nonpayable",
    inputs: [
      { name: "strategyId", type: "bytes32" },
      { name: "executionNonce", type: "uint256" },
      { name: "grossUsdc", type: "uint256" },
      { name: "poolIds", type: "bytes32[5]" },
      { name: "deadline", type: "uint256" },
      {
        name: "legs",
        type: "tuple[5]",
        components: [
          { name: "legIndex", type: "uint8" },
          { name: "adapter", type: "address" },
          { name: "tokenA", type: "address" },
          { name: "tokenB", type: "address" },
          { name: "tickLower", type: "int24" },
          { name: "tickUpper", type: "int24" },
          { name: "retainUsdc", type: "uint256" },
          {
            name: "swaps",
            type: "tuple[2]",
            components: [
              { name: "routeId", type: "bytes32" },
              { name: "grossUsdcIn", type: "uint256" },
              { name: "minOut", type: "uint256" },
              { name: "quotedOut", type: "uint256" },
              { name: "deadline", type: "uint256" },
            ],
          },
          { name: "swapCount", type: "uint8" },
          { name: "amountAMin", type: "uint256" },
          { name: "amountBMin", type: "uint256" },
          { name: "slippageBps", type: "uint256" },
        ],
      },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "exitLeg",
    stateMutability: "nonpayable",
    inputs: [
      { name: "strategyId", type: "bytes32" },
      {
        name: "leg",
        type: "tuple",
        components: [
          { name: "legIndex", type: "uint8" },
          { name: "adapter", type: "address" },
          { name: "tokenA", type: "address" },
          { name: "tokenB", type: "address" },
          { name: "positionTokenId", type: "uint256" },
          { name: "liquidity", type: "uint128" },
          { name: "amountAMin", type: "uint256" },
          { name: "amountBMin", type: "uint256" },
          { name: "slippageBps", type: "uint256" },
          { name: "fullExit", type: "bool" },
        ],
      },
      { name: "executionNonce", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "exitAll",
    stateMutability: "nonpayable",
    inputs: [
      { name: "strategyId", type: "bytes32" },
      {
        name: "legs",
        type: "tuple[5]",
        components: [
          { name: "legIndex", type: "uint8" },
          { name: "adapter", type: "address" },
          { name: "tokenA", type: "address" },
          { name: "tokenB", type: "address" },
          { name: "positionTokenId", type: "uint256" },
          { name: "liquidity", type: "uint128" },
          { name: "amountAMin", type: "uint256" },
          { name: "amountBMin", type: "uint256" },
          { name: "slippageBps", type: "uint256" },
          { name: "fullExit", type: "bool" },
        ],
      },
      { name: "executionNonceBase", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "exitAllToUsdc",
    stateMutability: "nonpayable",
    inputs: [
      { name: "strategyId", type: "bytes32" },
      {
        name: "legs",
        type: "tuple[5]",
        components: [
          { name: "legIndex", type: "uint8" },
          { name: "adapter", type: "address" },
          { name: "tokenA", type: "address" },
          { name: "tokenB", type: "address" },
          { name: "positionTokenId", type: "uint256" },
          { name: "liquidity", type: "uint128" },
          { name: "amountAMin", type: "uint256" },
          { name: "amountBMin", type: "uint256" },
          { name: "slippageBps", type: "uint256" },
          { name: "fullExit", type: "bool" },
        ],
      },
      {
        name: "swaps",
        type: "tuple[8]",
        components: [
          { name: "routeId", type: "bytes32" },
          { name: "amountIn", type: "uint256" },
          { name: "minOut", type: "uint256" },
          { name: "quotedOut", type: "uint256" },
          { name: "deadline", type: "uint256" },
        ],
      },
      { name: "swapCount", type: "uint8" },
      { name: "minUsdcOut", type: "uint256" },
      { name: "executionNonceBase", type: "uint256" },
    ],
    outputs: [{ name: "usdcOut", type: "uint256" }],
  },
  {
    type: "function",
    name: "emergencyExitLeg",
    stateMutability: "nonpayable",
    inputs: [
      { name: "strategyId", type: "bytes32" },
      {
        name: "leg",
        type: "tuple",
        components: [
          { name: "legIndex", type: "uint8" },
          { name: "adapter", type: "address" },
          { name: "tokenA", type: "address" },
          { name: "tokenB", type: "address" },
          { name: "positionTokenId", type: "uint256" },
          { name: "liquidity", type: "uint128" },
          { name: "amountAMin", type: "uint256" },
          { name: "amountBMin", type: "uint256" },
          { name: "slippageBps", type: "uint256" },
          { name: "fullExit", type: "bool" },
        ],
      },
      { name: "executionNonce", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "event",
    name: "StrategyExitToUsdcCompleted",
    inputs: [
      { name: "strategyId", type: "bytes32", indexed: true },
      { name: "user", type: "address", indexed: true },
      { name: "usdcOut", type: "uint256", indexed: false },
      { name: "executionNonceBase", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "StrategyDepositCompleted",
    inputs: [
      { name: "strategyId", type: "bytes32", indexed: true },
      { name: "user", type: "address", indexed: true },
      { name: "grossUsdc", type: "uint256", indexed: false },
      { name: "executionNonce", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "StrategyLegExited",
    inputs: [
      { name: "strategyId", type: "bytes32", indexed: true },
      { name: "legIndex", type: "uint256", indexed: true },
      { name: "poolId", type: "bytes32", indexed: true },
      { name: "positionTokenId", type: "uint256", indexed: false },
      { name: "emergency", type: "bool", indexed: false },
    ],
  },
] as const;

/** Concentrated-liquidity adapter view surface (real + MockConcentratedLiquidityAdapter). */
export const concentratedLiquidityAdapterAbi = [
  {
    type: "function",
    name: "closePosition",
    stateMutability: "nonpayable",
    inputs: [
      { name: "lpOwner", type: "address" },
      { name: "tokenId", type: "uint256" },
      { name: "recipient", type: "address" },
      { name: "tokenA", type: "address" },
      { name: "tokenB", type: "address" },
      { name: "amountAMin", type: "uint256" },
      { name: "amountBMin", type: "uint256" },
    ],
    outputs: [
      { name: "amountA", type: "uint256" },
      { name: "amountB", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "ownerOf",
    stateMutability: "view",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "positionTokens",
    stateMutability: "view",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [
      { name: "token0", type: "address" },
      { name: "token1", type: "address" },
    ],
  },
  {
    type: "function",
    name: "positionAmounts",
    stateMutability: "view",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [
      { name: "amount0", type: "uint256" },
      { name: "amount1", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "collectibleFees",
    stateMutability: "view",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [
      { name: "amount0", type: "uint256" },
      { name: "amount1", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "liquidityOf",
    stateMutability: "view",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [{ name: "", type: "uint128" }],
  },
  {
    type: "function",
    name: "positionManager",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "poolId",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "protocol",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
  },
  {
    type: "function",
    name: "getApproved",
    stateMutability: "view",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "approve",
    stateMutability: "nonpayable",
    inputs: [
      { name: "to", type: "address" },
      { name: "tokenId", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "event",
    name: "Transfer",
    inputs: [
      { name: "from", type: "address", indexed: true },
      { name: "to", type: "address", indexed: true },
      { name: "tokenId", type: "uint256", indexed: true },
    ],
  },
] as const;

export const strategyPermissionRegistryAbi = [
  {
    type: "function",
    name: "strategyIdFor",
    stateMutability: "view",
    inputs: [
      { name: "user", type: "address" },
      { name: "chainId", type: "uint256" },
      { name: "depositToken", type: "address" },
    ],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "getStrategy",
    stateMutability: "view",
    inputs: [{ name: "strategyId", type: "bytes32" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "user", type: "address" },
          { name: "chainId", type: "uint256" },
          { name: "depositToken", type: "address" },
          { name: "allowedActions", type: "uint256" },
          { name: "maxTotalPerTx", type: "uint256" },
          { name: "maxTotalPerDay", type: "uint256" },
          { name: "maxSlippageBps", type: "uint256" },
          { name: "minTimeBetweenExecutions", type: "uint256" },
          { name: "maxExecutionsPerDay", type: "uint256" },
          { name: "expiresAt", type: "uint256" },
          { name: "revoked", type: "bool" },
          { name: "paused", type: "bool" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "strategyDepositNonceUsed",
    stateMutability: "view",
    inputs: [
      { name: "strategyId", type: "bytes32" },
      { name: "executionNonce", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "registerFivePoolStrategy",
    stateMutability: "nonpayable",
    inputs: [
      {
        name: "strategy",
        type: "tuple",
        components: [
          { name: "user", type: "address" },
          { name: "chainId", type: "uint256" },
          { name: "depositToken", type: "address" },
          { name: "allowedActions", type: "uint256" },
          { name: "maxTotalPerTx", type: "uint256" },
          { name: "maxTotalPerDay", type: "uint256" },
          { name: "maxSlippageBps", type: "uint256" },
          { name: "minTimeBetweenExecutions", type: "uint256" },
          { name: "maxExecutionsPerDay", type: "uint256" },
          { name: "expiresAt", type: "uint256" },
          { name: "revoked", type: "bool" },
          { name: "paused", type: "bool" },
        ],
      },
      {
        name: "legPermissions",
        type: "tuple[5]",
        components: [
          { name: "user", type: "address" },
          { name: "chainId", type: "uint256" },
          { name: "poolId", type: "bytes32" },
          { name: "tokenA", type: "address" },
          { name: "tokenB", type: "address" },
          { name: "allowedActions", type: "uint256" },
          { name: "maxAmountPerTx", type: "uint256" },
          { name: "maxAmountPerDay", type: "uint256" },
          { name: "maxSlippageBps", type: "uint256" },
          { name: "minTimeBetweenExecutions", type: "uint256" },
          { name: "maxExecutionsPerDay", type: "uint256" },
          { name: "expiresAt", type: "uint256" },
          { name: "revoked", type: "bool" },
          { name: "paused", type: "bool" },
        ],
      },
      {
        name: "legs",
        type: "tuple[5]",
        components: [
          { name: "poolId", type: "bytes32" },
          { name: "allocationBps", type: "uint256" },
          { name: "adapter", type: "address" },
          { name: "tokenA", type: "address" },
          { name: "tokenB", type: "address" },
          { name: "legPermissionId", type: "bytes32" },
          { name: "maxLegPerTx", type: "uint256" },
          { name: "maxLegPerDay", type: "uint256" },
        ],
      },
    ],
    outputs: [{ name: "strategyId", type: "bytes32" }],
  },
  {
    type: "function",
    name: "getLeg",
    stateMutability: "view",
    inputs: [
      { name: "strategyId", type: "bytes32" },
      { name: "legIndex", type: "uint256" },
    ],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "poolId", type: "bytes32" },
          { name: "allocationBps", type: "uint256" },
          { name: "adapter", type: "address" },
          { name: "tokenA", type: "address" },
          { name: "tokenB", type: "address" },
          { name: "legPermissionId", type: "bytes32" },
          { name: "maxLegPerTx", type: "uint256" },
          { name: "maxLegPerDay", type: "uint256" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "revokeStrategy",
    stateMutability: "nonpayable",
    inputs: [{ name: "strategyId", type: "bytes32" }],
    outputs: [],
  },
] as const;

export const oracleGuardAbi = [
  {
    type: "function",
    name: "expectedAmountOut",
    stateMutability: "view",
    inputs: [
      { name: "tokenIn", type: "address" },
      { name: "tokenOut", type: "address" },
      { name: "amountIn", type: "uint256" },
      { name: "decimalsIn", type: "uint8" },
      { name: "decimalsOut", type: "uint8" },
    ],
    outputs: [{ name: "amountOut", type: "uint256" }],
  },
] as const;

/**
 * Uniswap V3 pool `slot0()` — 7 outputs including packed `feeProtocol`.
 * Do not use for Aerodrome Slipstream (6 outputs, no `feeProtocol`).
 */
export const uniswapV3PoolSlot0Abi = [
  {
    type: "function",
    name: "slot0",
    stateMutability: "view",
    inputs: [],
    outputs: [
      { name: "sqrtPriceX96", type: "uint160" },
      { name: "tick", type: "int24" },
      { name: "observationIndex", type: "uint16" },
      { name: "observationCardinality", type: "uint16" },
      { name: "observationCardinalityNext", type: "uint16" },
      { name: "feeProtocol", type: "uint8" },
      { name: "unlocked", type: "bool" },
    ],
  },
] as const;

/**
 * Aerodrome Slipstream CL pool `slot0()` — 6 outputs, no packed `feeProtocol`.
 * Do not use for Uniswap V3 (7 outputs).
 */
export const aerodromeSlipstreamPoolSlot0Abi = [
  {
    type: "function",
    name: "slot0",
    stateMutability: "view",
    inputs: [],
    outputs: [
      { name: "sqrtPriceX96", type: "uint160" },
      { name: "tick", type: "int24" },
      { name: "observationIndex", type: "uint16" },
      { name: "observationCardinality", type: "uint16" },
      { name: "observationCardinalityNext", type: "uint16" },
      { name: "unlocked", type: "bool" },
    ],
  },
] as const;

/** @deprecated Use uniswapV3PoolSlot0Abi or aerodromeSlipstreamPoolSlot0Abi via protocol routing. */
export const clPoolSlot0Abi = uniswapV3PoolSlot0Abi;

export const testPoolAdapterAbi = [
  ...erc20Abi,
  {
    type: "function",
    name: "poolId",
    stateMutability: "pure",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
  },
] as const;
