export const permissionRegistryAbi = [
  {
    type: "function",
    name: "permissionIdFor",
    stateMutability: "pure",
    inputs: [
      { name: "user", type: "address" },
      { name: "chainId", type: "uint256" },
      { name: "poolId", type: "bytes32" },
      { name: "tokenA", type: "address" },
      { name: "tokenB", type: "address" },
    ],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "registerPermission",
    stateMutability: "nonpayable",
    inputs: [
      {
        name: "perm",
        type: "tuple",
        components: [
          { name: "user", type: "address" },
          { name: "chainId", type: "uint256" },
          { name: "poolId", type: "bytes32" },
          { name: "tokenA", type: "address" },
          { name: "tokenB", type: "address" },
          { name: "allowedActions", type: "uint256" },
          { name: "maxAmountPerTx", type: "uint256" },
          { name: "maxAmountPerDay", type: "uint256" },
          { name: "maxSlippageBps", type: "uint256" },
          { name: "minTimeBetweenExecutions", type: "uint256" },
          { name: "maxExecutionsPerDay", type: "uint256" },
          { name: "expiresAt", type: "uint256" },
          { name: "revoked", type: "bool" },
          { name: "paused", type: "bool" },
        ],
      },
    ],
    outputs: [{ name: "permissionId", type: "bytes32" }],
  },
  {
    type: "function",
    name: "revoke",
    stateMutability: "nonpayable",
    inputs: [{ name: "permissionId", type: "bytes32" }],
    outputs: [],
  },
  {
    type: "function",
    name: "getPermission",
    stateMutability: "view",
    inputs: [{ name: "permissionId", type: "bytes32" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "user", type: "address" },
          { name: "chainId", type: "uint256" },
          { name: "poolId", type: "bytes32" },
          { name: "tokenA", type: "address" },
          { name: "tokenB", type: "address" },
          { name: "allowedActions", type: "uint256" },
          { name: "maxAmountPerTx", type: "uint256" },
          { name: "maxAmountPerDay", type: "uint256" },
          { name: "maxSlippageBps", type: "uint256" },
          { name: "minTimeBetweenExecutions", type: "uint256" },
          { name: "maxExecutionsPerDay", type: "uint256" },
          { name: "expiresAt", type: "uint256" },
          { name: "revoked", type: "bool" },
          { name: "paused", type: "bool" },
        ],
      },
    ],
  },
] as const;

export const stableClubExecutorAbi = [
  {
    type: "function",
    name: "depositAndAddLiquidity",
    stateMutability: "nonpayable",
    inputs: [
      { name: "permissionId", type: "bytes32" },
      { name: "executionNonce", type: "uint256" },
      { name: "adapter", type: "address" },
      { name: "stablecoin", type: "address" },
      { name: "tokenA", type: "address" },
      { name: "tokenB", type: "address" },
      { name: "depositAmount", type: "uint256" },
      { name: "swapAmount", type: "uint256" },
      { name: "minAmountOut", type: "uint256" },
      { name: "minLpOut", type: "uint256" },
      { name: "slippageBps", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "removeLiquidity",
    stateMutability: "nonpayable",
    inputs: [
      { name: "permissionId", type: "bytes32" },
      { name: "executionNonce", type: "uint256" },
      { name: "adapter", type: "address" },
      { name: "tokenA", type: "address" },
      { name: "tokenB", type: "address" },
      { name: "lpAmount", type: "uint256" },
      { name: "minAmountA", type: "uint256" },
      { name: "minAmountB", type: "uint256" },
      { name: "slippageBps", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "withdrawAll",
    stateMutability: "nonpayable",
    inputs: [
      { name: "permissionId", type: "bytes32" },
      { name: "executionNonce", type: "uint256" },
      { name: "adapter", type: "address" },
      { name: "tokenA", type: "address" },
      { name: "tokenB", type: "address" },
      { name: "lpAmount", type: "uint256" },
      { name: "minAmountA", type: "uint256" },
      { name: "minAmountB", type: "uint256" },
      { name: "slippageBps", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "pauseAutomation",
    stateMutability: "nonpayable",
    inputs: [{ name: "permissionId", type: "bytes32" }],
    outputs: [],
  },
  {
    type: "function",
    name: "revokePermission",
    stateMutability: "nonpayable",
    inputs: [{ name: "permissionId", type: "bytes32" }],
    outputs: [],
  },
  {
    type: "function",
    name: "emergencyExit",
    stateMutability: "nonpayable",
    inputs: [
      { name: "permissionId", type: "bytes32" },
      { name: "executionNonce", type: "uint256" },
      { name: "adapter", type: "address" },
      { name: "tokenA", type: "address" },
      { name: "tokenB", type: "address" },
      { name: "lpAmount", type: "uint256" },
      { name: "minAmountA", type: "uint256" },
      { name: "minAmountB", type: "uint256" },
    ],
    outputs: [],
  },
] as const;

export const erc20Abi = [
  {
    type: "function",
    name: "approve",
    stateMutability: "nonpayable",
    inputs: [
      { name: "spender", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "balanceOf",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "allowance",
    stateMutability: "view",
    inputs: [
      { name: "owner", type: "address" },
      { name: "spender", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
] as const;

export const testPoolAdapterAbi = [
  ...erc20Abi,
  {
    type: "function",
    name: "poolId",
    stateMutability: "pure",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
  },
] as const;
